## Best Practices for Importing Packages

In Python, importing packages like `numpy` is currently essential for mathematical and scientific computing. 

It's important to follow best practices for importing and using packages efficiently.

### 1. Standard Importing

`numpy` is commonly imported with an alias (`np`) to simplify function calls.

#### Best Practice:

You can import `numpy` or its submodules or functions with the following approaches

```python
import numpy as np # RECOMMENDED. accesses all of numpy's submodules and functions. call these functions with np.[submodule/function]
```

This convention (`np`) is widely used and makes your code cleaner and easier to read, especially for others who may be familiar with `numpy`.

### 2. Selective Importing

```python
from numpy import array, dot # import only specific functions
```

If you only need specific functions from `numpy`, import them directly to reduce namespace pollution. This can also make your code more efficient in some cases. The problem is that it requires you to be familiar with the submodules and functions in `numpy`, which we are still learning.

### 3. Avoid import *

While importing everything using `import *` might seem convenient, it can clutter the namespace and lead to conflicts with other libraries or functions. It’s also less clear which functions come from `numpy`.

```python
from numpy import * # NOT RECOMMENDED. this accesses all of numpy's submodules and functions, but the functions and submodules could potentially overwrite other loaded submodules and function
```
This practice makes your code harder to debug and understand and is **NOT RECOMMENDED.**

## Using Built-in Python Tools to Explore numpy

To learn more about numpy functions or objects, you can use Python’s built-in tools, which we have already played with, like `dir()`, `help()`.

### 1. `dir()` – List Available Functions and Attributes

The dir() function can be used to see all the functions and attributes available in numpy. This is helpful for exploring what the package offers.

#### Example:

In [1]:
import numpy as np
print(dir(np))  # Lists all functions and attributes in numpy (a bit overwhelming)

['False_', 'ScalarType', 'True_', '_CopyMode', '_NoValue', '__NUMPY_SETUP__', '__all__', '__array_api_version__', '__builtins__', '__cached__', '__config__', '__dir__', '__doc__', '__expired_attributes__', '__file__', '__former_attrs__', '__future_scalars__', '__getattr__', '__loader__', '__name__', '__numpy_submodules__', '__package__', '__path__', '__spec__', '__version__', '_core', '_distributor_init', '_expired_attrs_2_0', '_get_promotion_state', '_globals', '_int_extended_msg', '_mat', '_msg', '_no_nep50_warning', '_pyinstaller_hooks_dir', '_pytesttester', '_set_promotion_state', '_specific_msg', '_type_info', '_typing', '_utils', 'abs', 'absolute', 'acos', 'acosh', 'add', 'all', 'allclose', 'amax', 'amin', 'angle', 'any', 'append', 'apply_along_axis', 'apply_over_axes', 'arange', 'arccos', 'arccosh', 'arcsin', 'arcsinh', 'arctan', 'arctan2', 'arctanh', 'argmax', 'argmin', 'argpartition', 'argsort', 'argwhere', 'around', 'array', 'array2string', 'array_equal', 'array_equiv', 'arra

This will output a long list of available functions and objects within the numpy module.
### 2. help() – Detailed Documentation

The `help()` function provides a description of the module or function, including usage, parameters, and examples.

#### Example:

In [2]:
help(np.array)  # Get detailed documentation about the array function

Help on built-in function array in module numpy:

array(...)
    array(object, dtype=None, *, copy=True, order='K', subok=False, ndmin=0,
          like=None)
    
    Create an array.
    
    Parameters
    ----------
    object : array_like
        An array, any object exposing the array interface, an object whose
        ``__array__`` method returns an array, or any (nested) sequence.
        If object is a scalar, a 0-dimensional array containing object is
        returned.
    dtype : data-type, optional
        The desired data-type for the array. If not given, NumPy will try to use
        a default ``dtype`` that can represent the values (by applying promotion
        rules when necessary.)
    copy : bool, optional
        If ``True`` (default), then the array data is copied. If ``None``,
        a copy will only be made if ``__array__`` returns a copy, if obj is
        a nested sequence, or if a copy is needed to satisfy any of the other
        requirements (``dtype``, ``o

This will give you detailed information about how the `np.array()` function works, along with its parameters and examples.

#### Example:

In [ ]:
help(np.linalg)  # Get detailed documentation about the linalg submodule

This will give you detailed information about how the `np.linalg` submodule.

#### Example:

In [ ]:
help(np.linalg.eig)  # Get detailed documentation about the linalg.eig submodule

## Introduction to Linear Algebra with numpy

While Python lists can be used to represent vectors and matrices, `numpy` provides a more efficient and intuitive way to perform linear algebra operations.

In this section, we will introduce the main matrix operations in `numpy`, compare them with native Python `list` operations, and see why `numpy` is the preferred tool for linear algebra.

### Creating Vectors and Matrices in Python and numpy

In Python, you can create vectors and matrices using lists or nested lists. However, performing mathematical operations like addition, multiplication, or dot products can be cumbersome.

`numpy` simplifies this by providing the array object, which represents vectors and matrices and allows for efficient mathematical operations.

#### Creating Vectors and Matrices with Lists (Native Python)

In [3]:
# Creating a vector and a matrix using lists (Native Python)
vector = [1, 2, 3]  # A simple vector
matrix = [[1, 2], [3, 4]]  # A 2x2 matrix

# Displaying the vector and matrix
print("Vector:", vector)
print("Matrix:", matrix)


Vector: [1, 2, 3]
Matrix: [[1, 2], [3, 4]]


### Creating Vectors and Matrices with `numpy`

In [5]:
import numpy as np

# Creating a vector and a matrix using numpy arrays
vector_np = np.array([1, 2, 3])
matrix_np = np.array([[1, 2], [3, 4]])

# Displaying the numpy vector and matrix
print("Numpy Vector:\n", vector_np)
print("Numpy Matrix:\n", matrix_np)


Numpy Vector:
 [1 2 3]
Numpy Matrix:
 [[1 2]
 [3 4]]


### Matrix Operations: Native Python vs `numpy`

In native Python, performing operations like addition, multiplication, or dot products on lists requires explicit loops or list comprehensions. `numpy` allows you to perform these operations directly on arrays, making the code more concise and efficient.
#### Common Matrix Operations:

    Addition: Adding two matrices.
    Matrix Multiplication: Multiplying two matrices.
    Dot Product: Computing the dot product of two vectors.

#### Addition: Native Python vs `numpy`

In [6]:
# Matrix Addition with Native Python
matrix1 = [[1, 2], [3, 4]]
matrix2 = [[5, 6], [7, 8]]

# Manually adding two matrices (native Python)
result_matrix = matrix1 + matrix2
print("The + operation actually concatenates these matrices:\n", result_matrix)

# Matrix Addition with numpy
matrix1_np = np.array([[1, 2], [3, 4]])
matrix2_np = np.array([[5, 6], [7, 8]])

result_matrix_np = matrix1_np + matrix2_np  # Numpy handles matrix addition directly
print("Matrix Addition (Numpy):\n", result_matrix_np)


The + operation actually concatenates these matrices:
 [[1, 2], [3, 4], [5, 6], [7, 8]]
Matrix Addition (Numpy):
 [[ 6  8]
 [10 12]]


### Matrix Multiplication in `numpy`

**You'll need to comment out the native python lines. They won't work**

In [7]:
# Matrix multiplication with Native Python
matrix1 = [[1, 2], [3, 4]]
matrix2 = [[5, 6], [7, 8]]

# Manually performing matrix multiplication (nested loops)
result_matrix = matrix1 * matrix2
print("Matrix Multiplication (Native Python):\n", result_matrix)

# Matrix multiplication with numpy
matrix1_np = np.array([[1, 2], [3, 4]])
matrix2_np = np.array([[5, 6], [7, 8]])

result_matrix_np = np.dot(matrix1_np, matrix2_np)  # Numpy uses dot() for matrix multiplication
print("Matrix Multiplication (Numpy):\n", result_matrix_np)


TypeError: can't multiply sequence by non-int of type 'list'

### Dot Product in `numpy`

In [ ]:
# Dot product with numpy
vector1_np = np.array([1, 2, 3])
vector2_np = np.array([4, 5, 6])

dot_product_np = np.dot(vector1_np, vector2_np)  # Numpy handles dot product directly
print("Dot Product (Numpy):", dot_product_np)

## Common numpy Operations and Linear Algebra Tools

`numpy` is not only great for working with arrays, but it also provides powerful linear algebra capabilities through the `numpy.linalg` module. Here are some of the most common `numpy` operations for matrices and arrays, as well as key linear algebra functions like determinants, matrix inversion, and solving linear systems.

### Common numpy Operations for Arrays and Matrices

`numpy` offers a wide variety of functions that allow for easy manipulation of arrays and matrices. Some of the most common operations include:
#### 1. Array Creation

*    `np.array()`: Create an array from a list or nested list.
*    `np.zeros()`: Create an array of all zeros.
*    `np.ones()`: Create an array of all ones.
*    `np.eye()`: Create an identity matrix.

#### 2. Element-wise Operations

*    `+`, `-`, `*`, `/`: Basic arithmetic operations are applied element-wise between two arrays.
*    `np.sqrt()`: Calculate the square root of each element in an array.
*    `np.exp()`: Exponentiate each element in the array.

#### 3. Statistical Functions

*    `np.sum()`: Compute the sum of array elements.
*    `np.mean()`: Compute the mean (average) of array elements.
*    `np.std()`: Compute the standard deviation.

#### 4. Matrix Operations

*    `np.transpose()`: Transpose of a matrix (swap rows and columns). You can also use `A.T` for a matrix A
*    `np.conjugate()`: Conjugate of a matrix. Use `.conj().T` or `np.conjugate(array).T` for the conjugate-transpose/Hermitian conjugate
*    `np.dot()`: Matrix multiplication or dot product.
*    `@`: Matrix multiplication or dot product.

### Examples of Common Array Operations

In [ ]:
import numpy as np

# Create a matrix (2D array)
matrix = np.array([[1, 2], [3, 4]])

# Create some special arrays
zeros_matrix = np.zeros((2, 2))  # A 2x2 matrix of zeros
ones_matrix = np.ones((2, 3))    # A 2x3 matrix of ones
identity_matrix = np.eye(3)      # A 3x3 identity matrix

# Perform element-wise operations
elementwise_addition = matrix + np.array([[5, 6], [7, 8]])  # Element-wise addition
elementwise_multiplication = matrix * 2  # Element-wise multiplication by 2
elementwise_sqrt = np.sqrt(matrix)  # Element-wise square root

# Print the results
print("Matrix:\n", matrix)
print("\nZeros Matrix:\n", zeros_matrix)
print("\nOnes Matrix:\n", ones_matrix)
print("\nIdentity Matrix:\n", identity_matrix)
print("\nElement-wise Addition:\n", elementwise_addition)
print("\nElement-wise Multiplication by 2:\n", elementwise_multiplication)
print("\nElement-wise Square Root:\n", elementwise_sqrt)


### Linear Algebra with `numpy.linalg`

`numpy` also provides a set of linear algebra functions through the `numpy.linalg` module, which makes it easy to perform complex matrix operations.

#### 1. Matrix Inversion

* `np.linalg.inv()`: Computes the inverse of a square matrix.

#### 2. Determinants

* `np.linalg.det()`: Computes the determinant of a matrix.

#### 3. Eigenvalues and Eigenvectors

* `np.linalg.eig()`: Computes the eigenvalues and eigenvectors of a matrix.

#### 4. Solving Systems of Linear Equations

* `np.linalg.solve()`: Solves the system of linear equations Ax = b for x.

### Examples of Linear Algebra Operations

In [ ]:
import numpy as np

# Create a 2x2 matrix
matrix = np.array([[1, 2], [3, 4]])

# Inverse of the matrix
inverse_matrix = np.linalg.inv(matrix)

# Determinant of the matrix
determinant = np.linalg.det(matrix)

# Eigenvalues and eigenvectors
eigenvalues, eigenvectors = np.linalg.eig(matrix)

# Solve the system Ax = b
A = np.array([[3, 1], [1, 2]])
b = np.array([9, 8])
x = np.linalg.solve(A, b)

# Print the results
print("Matrix:\n", matrix)
print("\nInverse of the Matrix:\n", inverse_matrix)
print("\nDeterminant of the Matrix:\n", determinant)
print("\nEigenvalues:\n", eigenvalues)
print("\nEigenvectors:\n", eigenvectors)
print("\nSolution to the system Ax = b:\n", x)
